version: '3.8'
services:
  spark-master:
    image: bitnami/spark:latest
    container_name: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
    volumes:
      - ./data:/bitnami/spark/data
      - ./zipcodes.csv:/bitnami/spark/zipcodes.csv  # New volume mapping for zipcode.csv

  spark-worker:
    image: bitnami/spark:latest
    container_name: spark-worker
    depends_on:
      - spark-master
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
    volumes:
      - ./data:/bitnami/spark/data
      - ./zipcodes.csv:/bitnami/spark/zipcodes.csv  # New volume mapping for zipcode.csv
